# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - devel

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

# Build your code
script:
  - echo 'Dummy build'

after_success:
  - (cat Doxyfile ; echo "OUTPUT_DIRECTORY=") | doxygen -

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: devel